name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name  "dwekjem"
          git config user.email "derekrneilson@gmail.com"

      - name: Debug GH_TOKEN and Deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "GH_TOKEN prefix: ${GH_TOKEN:0:8}…"
          DEBUG=gh-pages npm run deploy --