name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPLOY_KEY }} # Use the default GITHUB_TOKEN if the secret is not set

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Debug GH_TOKEN and Deploy
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_KEY }} # Use the default GITHUB_TOKEN if deploy key is not available
        run: |
          echo "GH_TOKEN prefix: ${GH_TOKEN:0:8}…"
          DEBUG=gh-pages npm run deploy --